function [feat]=getfeatures_tnt(z)
[r2,c2]=size(z);  %2
chngover=bracket2_t_nt(z);%1
dens=density(z);%1
 eul=euler_t_nt(z);%1
[r2,c2]=size(z);
 A=z(1:floor(r2/2),1:floor(c2/2));
 B=z(1:floor(r2/2),floor(c2/2)+1:c2);
 C=z(floor(r2/2)+1:r2,1:floor(c2/2));
 D=z(floor(r2/2)+1:r2,floor(c2/2)+1:c2);
 eul2=euler_t_nt(A);
 eul3=euler_t_nt(B);
 eul4=euler_t_nt(C);
 eul5=euler_t_nt(D);%4
attrib_new1=noIntersectionsAndDistFarPixelCornerEWNSDir(z);%4
attrib_new2=noIntersectionsAndDistFarPixelEWNSDir(z);%4
%l=line(z);%1
%t=test(z);%4
%x=getSirFeature(z);%17
feat=horzcat(r2,c2,dens,chngover,eul,eul2,eul3,eul4,eul5,attrib_new1,attrib_new2);